---
- name: Create FRR config dir
  ansible.builtin.file:
    path: "{{ frr_conf_dest }}"
    state: "directory"
    owner: "{{ frr_user }}"
    group: "{{ frr_group }}"
    mode: "0750"

- name: Create configuration for daemons
  ansible.builtin.template:
    src: "daemons.j2"
    dest: "{{ frr_conf_dest + '/' + frr_daemons_file }}"
    owner: "{{ frr_user }}"
    group: "{{ frr_group }}"
    mode: "0640"
  notify:
    - "Restart frr"

- name: Template vtysh.conf
  template:
    src: "vtysh.conf.j2"
    dest: "{{ frr_conf_dest }}/vtysh.conf"
  notify:
    - Restart frr
  
- name: Template frr.conf
  ansible.builtin.template:
    src: "frr.j2"
    dest: "{{ frr_conf_dest + '/frr.conf' }}"
    owner: "{{ frr_user }}"
    group: "{{ frr_group }}"
    mode: "0640"
    #validate: "vtysh -C -f %s"
  notify:
    - "Restart frr"

- name: Enable FRR service
  ansible.builtin.systemd:
    name: "{{ frr_service }}"
    enabled: "yes"
  when: >-
    frr_enable | bool
