---
- name: frr | Deploy frr daemons
  ansible.builtin.template:
    src: "daemons.j2"
    dest: "{{ frr_conf_dest + '/' + frr_daemons_file }}"
    owner: "{{ frr_user }}"
    group: "{{ frr_group }}"
    mode: "0640"
  notify:
    - "Restart frr"

- name: Template vtysh.conf
  template:
    src: "vtysh.conf.j2"
    dest: "{{ frr_conf_dest }}/vtysh.conf"
  notify:
    - Restart frr
  
- name: frr | Deploy frr configuration
  ansible.builtin.template:
    src: "frr.j2"
    dest: "{{ frr_conf_dest + '/frr.conf' }}"
    owner: "{{ frr_user }}"
    group: "{{ frr_group }}"
    mode: "0640"
    #validate: "vtysh -C -f %s"
  notify:
    - "Restart frr"

- name: frr | Enable frr service
  ansible.builtin.systemd:
    name: "{{ frr_service }}"
    enabled: "yes"
  when:
    - frr is defined
    - frr != ''
  #   - "hostvars[inventory_hostname]['frr'] |
  #      community.general.json_query(vars['frr_enable']) is defined"
  #   - "hostvars[inventory_hostname]['frr'] |
  #      community.general.json_query(vars['frr_enable']) == 'true'"
  # vars:
  #   frr_enable: "[] | map(&enable || 'false', @) | [0]"
