---
- name: Combine default vars
  set_fact:
    frr: "{{ frr_defaults | combine(frr, recursive=True) }}"

- name: frr | Add the OS specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yml"
    
- include_tasks: "install.yaml"
  when: >-
    frr_install

- name: Clean configuration
  include_tasks: "clean_configuration.yaml"
  when: >-
    frr_configure
    and frr_clean_configuration

- name: Configure FRR
  include_tasks: "configure.yaml"
  when: >-
    frr_configure
