---
- ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - frr is defined
    - frr != ''
    - frr.install_package
- ansible.builtin.import_tasks:
    file: "deploy_frr.yml"
