---
- name: Combine default vars
  set_fact:
    frr: "{{ frr_defaults | combine(frr, recursive=True) }}"

# - debug: var=frr
# - pause:
- name: frr | Add the OS specific variables
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family + '.yml' }}"
# - name: frr | Set facts about frr role
#   ansible.builtin.set_fact:
#     frr_daemons_settings: "{{ frr.daemons }}"
#     frr_vtysh_settings: "{{ frr.vtysh_options }}"
#     frr_init_settings: "{{ frr.init_options }}"
#     frr_zebra_settings: "{{ frr.settings.zebra }}"
#     frr_vty_settings: "{{ frr.settings.vty }}"
#     frr_routes: "{{ frr.settings.routes }}"
#     frr_vrrp: "{{ frr.settings.vrrp }}"
#     frr_interfaces: "{{ frr.settings.interfaces }}"
#     frr_router_ospf_settings: "{{ frr.settings.router.ospf }}"
#     frr_router_bgp_settings: "{{ frr.settings.router.bgp }}"
#     frr_router_bgp_access_lists: "{{ frr.settings.router.bgp_as_path_access_list }}"
#     frr_router_route_maps: "{{ frr.settings.router.route_map }}"
#     frr_router_access_lists: "{{ frr.settings.router.access_list }}"
#     frr_router_prefix_lists: "{{ frr.settings.router.prefix_list }}"
- name: frr | Create frr catalog
  ansible.builtin.file:
    path: "{{ frr_conf_dest }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0750"
